// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: bots_telegram.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBotTelegram = `-- name: CreateBotTelegram :one
INSERT INTO botsTelegram (id, created_at, updated_at, name, bot_token, chat_id, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, name, bot_token, chat_id, user_id
`

type CreateBotTelegramParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	BotToken  string
	ChatID    string
	UserID    uuid.UUID
}

func (q *Queries) CreateBotTelegram(ctx context.Context, arg CreateBotTelegramParams) (Botstelegram, error) {
	row := q.db.QueryRowContext(ctx, createBotTelegram,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.BotToken,
		arg.ChatID,
		arg.UserID,
	)
	var i Botstelegram
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.BotToken,
		&i.ChatID,
		&i.UserID,
	)
	return i, err
}
