// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Botstelegram struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	BotToken  string
	ChatID    string
	UserID    uuid.UUID
}

type Newselement struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	SiteParseID uuid.UUID
	Title       string
	NewsDate    string
	Url         string
}

type Siteparse struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	UrlSite       string
	Type          string
	LastFetchedAt sql.NullTime
}

type Siteparsefollow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
	SiteParseID uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ApiKey    string
}
