// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: site_parse.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSiteParse = `-- name: CreateSiteParse :one
INSERT INTO siteParse (id, created_at, updated_at, name, url_site, type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, name, url_site, type
`

type CreateSiteParseParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	UrlSite   string
	Type      string
}

func (q *Queries) CreateSiteParse(ctx context.Context, arg CreateSiteParseParams) (Siteparse, error) {
	row := q.db.QueryRowContext(ctx, createSiteParse,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.UrlSite,
		arg.Type,
	)
	var i Siteparse
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.UrlSite,
		&i.Type,
	)
	return i, err
}
